/**
 * Interactive Project Setup Script
 *
 * This script helps you configure your Next.js project with Claude Code capabilities.
 * It will:
 * - Ask for Supabase credentials
 * - Ask for N8N credentials (optional)
 * - Generate .env.local
 * - Generate .claude/.mcp.json
 * - Initialize Supabase with exec_sql function
 */

import * as fs from 'fs';
import * as path from 'path';
import * as readline from 'readline';
import { fileURLToPath } from 'url';
import { dirname } from 'path';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const projectRoot = path.join(__dirname, '..');

const rl = readline.createInterface({
  input: process.stdin,
  output: process.stdout
});

function question(query) {
  return new Promise(resolve => rl.question(query, resolve));
}

async function main() {
  console.log('╔════════════════════════════════════════════════════════════╗');
  console.log('║   Next.js + Claude Code Template - Project Setup          ║');
  console.log('╚════════════════════════════════════════════════════════════╝\n');

  console.log('This script will help you configure your project.\n');

  // Project name
  const projectName = await question('Project name (default: my-app): ') || 'my-app';

  // Supabase configuration
  console.log('\n📊 Supabase Configuration');
  console.log('─'.repeat(60));

  const useSupabase = (await question('Use Supabase? (Y/n): ')).toLowerCase() !== 'n';

  let supabaseUrl = '';
  let supabaseAnonKey = '';
  let supabaseServiceKey = '';
  let supabaseProjectId = '';

  if (useSupabase) {
    supabaseUrl = await question('Supabase URL (https://xxx.supabase.co): ');
    supabaseAnonKey = await question('Supabase Anon Key: ');
    supabaseServiceKey = await question('Supabase Service Role Key: ');

    // Extract project ID from URL
    const urlMatch = supabaseUrl.match(/https:\/\/([^.]+)\.supabase\.co/);
    supabaseProjectId = urlMatch ? urlMatch[1] : await question('Supabase Project ID: ');
  }

  // N8N configuration
  console.log('\n🤖 N8N Configuration (Optional)');
  console.log('─'.repeat(60));

  const useN8N = (await question('Use N8N? (y/N): ')).toLowerCase() === 'y';

  let n8nUrl = '';
  let n8nApiKey = '';

  if (useN8N) {
    n8nUrl = await question('N8N API URL: ');
    n8nApiKey = await question('N8N API Key: ');
  }

  // Turbopack or Bun
  console.log('\n⚡ Build Tool');
  console.log('─'.repeat(60));

  const buildTool = await question('Use Turbopack or Bun? (turbopack/bun, default: turbopack): ') || 'turbopack';

  // Generate .env.local
  console.log('\n📝 Generating .env.local...');

  const envContent = `# ========================================
# ${projectName} - Environment Variables
# Generated by setup script on ${new Date().toISOString()}
# ========================================

# ========================================
# Supabase Configuration
# ========================================
${useSupabase ? `
NEXT_PUBLIC_SUPABASE_URL=${supabaseUrl}
NEXT_PUBLIC_SUPABASE_ANON_KEY=${supabaseAnonKey}
SUPABASE_SERVICE_ROLE_KEY=${supabaseServiceKey}
SUPABASE_PROJECT_ID=${supabaseProjectId}
` : '# Supabase is disabled'}

${useN8N ? `# ========================================
# N8N Configuration
# ========================================

N8N_API_URL=${n8nUrl}
N8N_API_KEY=${n8nApiKey}
` : '# N8N is disabled'}

# ========================================
# Application Configuration
# ========================================

NODE_ENV=development
NEXT_PUBLIC_APP_URL=http://localhost:3000
`;

  fs.writeFileSync(path.join(projectRoot, '.env.local'), envContent);
  console.log('✅ .env.local created');

  // Generate .claude/.mcp.json
  if (useSupabase || useN8N) {
    console.log('\n📝 Generating .claude/.mcp.json...');

    const mcpConfig = {
      mcpServers: {}
    };

    if (useN8N) {
      mcpConfig.mcpServers['n8n-mcp'] = {
        command: 'docker',
        args: [
          'run',
          '-i',
          '--rm',
          '--init',
          '-e',
          'MCP_MODE=stdio',
          '-e',
          'N8N_MCP_TELEMETRY_DISABLED=true',
          '-e',
          'LOG_LEVEL=error',
          '-e',
          'DISABLE_CONSOLE_OUTPUT=true',
          '-e',
          `N8N_API_URL=${n8nUrl}`,
          '-e',
          `N8N_API_KEY=${n8nApiKey}`,
          'ghcr.io/czlonkowski/n8n-mcp:latest'
        ]
      };
    }

    if (useSupabase) {
      mcpConfig.mcpServers['supabase'] = {
        command: 'npx',
        args: ['-y', '@supabase/mcp-server-supabase'],
        env: {
          SUPABASE_URL: supabaseUrl,
          SUPABASE_SERVICE_ROLE_KEY: supabaseServiceKey
        }
      };
    }

    const claudeDir = path.join(projectRoot, '.claude');
    if (!fs.existsSync(claudeDir)) {
      fs.mkdirSync(claudeDir, { recursive: true });
    }

    fs.writeFileSync(
      path.join(claudeDir, '.mcp.json'),
      JSON.stringify(mcpConfig, null, 2)
    );

    console.log('✅ .claude/.mcp.json created');
  }

  // Update package.json scripts
  console.log('\n📝 Updating package.json...');

  const packageJsonPath = path.join(projectRoot, 'package.json');
  const packageJson = JSON.parse(fs.readFileSync(packageJsonPath, 'utf8'));

  packageJson.name = projectName;

  if (buildTool === 'bun') {
    packageJson.scripts.dev = 'bun --bun next dev';
  }

  fs.writeFileSync(packageJsonPath, JSON.stringify(packageJson, null, 2));
  console.log('✅ package.json updated');

  // Summary
  console.log('\n╔════════════════════════════════════════════════════════════╗');
  console.log('║   ✅ Project Setup Complete!                              ║');
  console.log('╚════════════════════════════════════════════════════════════╝\n');

  console.log('📊 Configuration Summary:');
  console.log(`   Project: ${projectName}`);
  console.log(`   Supabase: ${useSupabase ? '✅ Enabled' : '❌ Disabled'}`);
  console.log(`   N8N: ${useN8N ? '✅ Enabled' : '❌ Disabled'}`);
  console.log(`   Build Tool: ${buildTool}`);

  console.log('\n🚀 Next Steps:\n');

  console.log('1. Install dependencies:');
  console.log('   npm install');
  console.log('');

  if (useSupabase) {
    console.log('2. Initialize Supabase (create exec_sql function):');
    console.log('   npm run init:supabase');
    console.log('');
    console.log('3. Generate TypeScript types:');
    console.log('   npm run gen:types');
    console.log('');
  }

  console.log(`${useSupabase ? '4' : '2'}. Start the development server:`);
  console.log(`   npm run dev${buildTool === 'bun' ? ' (using Bun)' : ' (using Turbopack)'}`);
  console.log('');

  console.log('💡 Tips:');
  console.log('   - Read README.md for detailed documentation');
  console.log('   - Check .claude/commands/ for available slash commands');
  console.log('   - Use Claude Code for autonomous development!');
  console.log('');

  rl.close();
}

main().catch(error => {
  console.error('\n💥 Error:', error);
  rl.close();
  process.exit(1);
});
